import type { Metadata } from "next";
import { BellRing, Bot, CircleDollarSign, FileCheck2, Landmark, Users } from "lucide-react";
import { SolutionDetail } from "@/components/landing/solution-detail";
import { getLocale } from "@/lib/i18n/server";

export const metadata: Metadata = { title: "Solution Entreprise | AskFinance AI", description: "Copilote de trésorerie pour TPE, PME et équipes finance." };
const icons=[Landmark,CircleDollarSign,BellRing,Users,FileCheck2,Bot] as const;
const copies={
 fr:{eyebrow:"B2B · Entreprise",title:"Pilotez la trésorerie avant qu’elle ne vous pilote.",description:"Un espace de travail pour rapprocher les flux réels, les encaissements attendus, les échéances et les décisions de l’équipe.",promise:"Voir le risque assez tôt pour préparer l’action, la validation et le suivi.",blocks:[["Trésorerie multi-compte","Soldes d’ouverture, vue consolidée et virements internes neutralisés dans les indicateurs."],["Facture à paiement","Échéances, paiements partiels ou complets et brouillons de relance."],["Inbox financière","Budgets, impayés, anomalies récurrentes, fiscalité indicative et risque de découvert."],["Rôles et validations","Lecture seule, contribution, administration et demandes de validation."],["Audit et préparation","Journal des actions sensibles et checklist facture électronique."],["Yassia à outils","Trois personas pour sécuriser, arbitrer ou projeter à partir des données de l’espace."]],steps:["Créez l’espace Entreprise et renseignez son profil.","Ajoutez les comptes puis importez les relevés CSV.","Déclarez les encaissements attendus et ajustez les budgets mensuels.","Traitez l’inbox, préparez les validations et interrogez Yassia."],note:"Les provisions fiscales et les échéances proposées sont indicatives. AskFinance aide au pilotage mais ne remplace pas la validation d’un expert-comptable, d’un DAF ou d’un conseil juridique."},
 en:{eyebrow:"B2B · Business",title:"Manage cash flow before it manages you.",description:"A workspace that brings together actual flows, expected receivables, deadlines and team decisions.",promise:"See risk early enough to prepare the action, approval and follow-up.",blocks:[["Multi-account cash","Opening balances, consolidated view and internal transfers excluded from indicators."],["Invoice to payment","Due dates, partial or full payments and reminder drafts."],["Financial inbox","Budgets, overdue invoices, recurring anomalies, indicative tax and overdraft risk."],["Roles and approvals","Read-only, contribution, administration and approval requests."],["Audit and readiness","Sensitive-action log and e-invoicing checklist."],["Tool-enabled Yassia","Three personas to protect, arbitrate or project using workspace data."]],steps:["Create a Business workspace and complete its profile.","Add accounts, then import CSV statements.","Declare expected receivables and adjust monthly budgets.","Handle the inbox, prepare approvals and ask Yassia."],note:"Suggested tax provisions and deadlines are indicative. AskFinance supports management but does not replace approval by an accountant, CFO or legal adviser."},
 uk:{eyebrow:"B2B · Бізнес",title:"Керуйте ліквідністю, перш ніж вона почне керувати вами.",description:"Робочий простір, що поєднує фактичні потоки, очікувані надходження, строки й командні рішення.",promise:"Побачте ризик завчасно, щоб підготувати дію, погодження та контроль.",blocks:[["Кошти на кількох рахунках","Початкові баланси, зведений огляд і виключення внутрішніх переказів із показників."],["Від рахунку до оплати","Строки, часткові або повні платежі й чернетки нагадувань."],["Фінансова скринька","Бюджети, прострочення, регулярні аномалії, орієнтовні податки й ризик овердрафту."],["Ролі та погодження","Перегляд, участь, адміністрування й запити на погодження."],["Аудит і підготовка","Журнал чутливих дій і список готовності до е-рахунків."],["Yassia з інструментами","Три персони для захисту, балансування або прогнозування на основі даних простору."]],steps:["Створіть бізнес-простір і заповніть профіль.","Додайте рахунки, потім імпортуйте CSV-виписки.","Зазначте очікувані надходження й налаштуйте місячні бюджети.","Опрацюйте скриньку, підготуйте погодження й запитайте Yassia."],note:"Запропоновані податкові резерви й строки є орієнтовними. AskFinance допомагає керувати, але не замінює перевірку бухгалтером, фінансовим директором або юристом."},
} as const;
export default function BusinessPage(){const c=copies[getLocale()];return <SolutionDetail eyebrow={c.eyebrow} title={c.title} description={c.description} promise={c.promise} blocks={c.blocks.map(([title,description],i)=>({icon:icons[i],title,description}))} steps={[...c.steps]} note={c.note}/>;}
