import { Database, FileKey2, KeyRound, LockKeyhole, ScanSearch, ShieldCheck, Trash2, UserRoundCog } from "lucide-react";

import { PageHero } from "@/components/landing/page-hero";
import { PublicShell } from "@/components/landing/public-shell";
import { Reveal } from "@/components/landing/reveal";
import { getLocale } from "@/lib/i18n/server";

const icons=[KeyRound,Database,UserRoundCog,FileKey2,ScanSearch,Trash2] as const;
const copies={
 fr:{eyebrow:"Sécurité et confiance",title:"Dire précisément ce qui protège vos données.",intro:"AskFinance applique plusieurs barrières complémentaires. Cette page décrit l’architecture actuelle sans promettre un chiffrement de bout en bout ou un lieu d’hébergement non encore contractualisé.",controls:[["Authentification centralisée","Supabase Auth émet les sessions ; l’API vérifie les jetons avant tout accès métier."],["Isolation par espace","Les politiques RLS filtrent les lectures et écritures selon l’appartenance à l’espace."],["Permissions par rôle","Viewer, member, admin et owner limitent les actions possibles dans l’interface et côté serveur."],["Transit CSV privé","Le fichier est envoyé dans un bucket privé, traité par l’API puis supprimé en succès comme en échec."],["Journal d’audit","Les actions sensibles, validations et changements de rôle laissent une trace exploitable."],["Suppression contrôlée","La suppression d’un compte bancaire demande confirmation et annonce les données associées."]],active:"Ce qui est actif",activeItems:["Authentification et rafraîchissement de session","RLS sur les données utilisateur et d’espace","Bucket d’import privé avec chemin par utilisateur","Contrôles serveur sur les écritures sensibles"],todo:"À finaliser avant production",todoItems:["Choix et documentation des régions d’hébergement","Durées de conservation contractuelles","Procédure de réponse aux incidents","Registre des sous-traitants et transferts éventuels"],note:"Aucun identifiant bancaire n’est demandé aujourd’hui : la synchronisation bancaire est volontairement reportée. Les imports reposent sur des fichiers CSV fournis explicitement par l’utilisateur."},
 en:{eyebrow:"Security and trust",title:"State precisely what protects your data.",intro:"AskFinance applies several complementary safeguards. This page describes the current architecture without promising end-to-end encryption or a hosting location that has not yet been contracted.",controls:[["Centralized authentication","Supabase Auth issues sessions; the API verifies tokens before any business-data access."],["Workspace isolation","RLS policies filter reads and writes according to workspace membership."],["Role-based permissions","Viewer, member, admin and owner roles limit actions in the interface and on the server."],["Private CSV transit","The file is sent to a private bucket, processed by the API and deleted on success or failure."],["Audit log","Sensitive actions, approvals and role changes leave an actionable trace."],["Controlled deletion","Deleting a bank account requires confirmation and lists the associated data."]],active:"Currently active",activeItems:["Authentication and session refresh","RLS on user and workspace data","Private import bucket with a per-user path","Server-side checks for sensitive writes"],todo:"To finalize before production",todoItems:["Select and document hosting regions","Contractual retention periods","Incident response procedure","Register of processors and potential transfers"],note:"No bank credentials are requested today: bank synchronization has deliberately been postponed. Imports use CSV files explicitly supplied by the user."},
 uk:{eyebrow:"Безпека й довіра",title:"Точно пояснюємо, що захищає ваші дані.",intro:"AskFinance застосовує кілька взаємодоповнювальних бар’єрів. Тут описано поточну архітектуру без обіцянок наскрізного шифрування чи ще не погодженого місця хостингу.",controls:[["Централізована автентифікація","Supabase Auth створює сесії; API перевіряє токени перед доступом до бізнес-даних."],["Ізоляція просторів","Політики RLS фільтрують читання й запис відповідно до участі в просторі."],["Дозволи за ролями","Ролі viewer, member, admin та owner обмежують дії в інтерфейсі й на сервері."],["Приватне передавання CSV","Файл надсилається в приватний bucket, обробляється API й видаляється незалежно від результату."],["Журнал аудиту","Чутливі дії, погодження та зміни ролей залишають придатний для перевірки слід."],["Контрольоване видалення","Видалення банківського рахунку потребує підтвердження й показує пов’язані дані."]],active:"Що вже працює",activeItems:["Автентифікація й оновлення сесії","RLS для даних користувача та простору","Приватний bucket імпорту зі шляхом користувача","Серверні перевірки чутливих записів"],todo:"Що завершити до запуску",todoItems:["Обрати й задокументувати регіони хостингу","Договірні строки зберігання","Процедура реагування на інциденти","Реєстр обробників і можливих передач"],note:"Сьогодні банківські облікові дані не запитуються: синхронізацію з банком свідомо відкладено. Імпорт виконується з CSV-файлів, які користувач надає явно."},
} as const;

export default function SecurityPage(){const copy=copies[getLocale()];const controls=icons.map((Icon,i)=>[Icon,copy.controls[i][0],copy.controls[i][1]] as const);return <PublicShell>
  <PageHero eyebrow={copy.eyebrow} title={copy.title} description={copy.intro}/>
  <section className="bg-slate-950 py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-5 px-4 sm:px-6 md:grid-cols-2 lg:grid-cols-3 lg:px-8">{controls.map(([Icon,title,text],index)=><Reveal key={title} delay={(index%3)*0.06} className="rounded-2xl border border-white/10 bg-white/[0.035] p-6"><Icon className="h-6 w-6 text-teal"/><h2 className="mt-5 font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></Reveal>)}</div></section>
  <section className="border-y border-white/10 bg-slate-900/50 py-20"><div className="mx-auto grid max-w-5xl gap-6 px-4 sm:px-6 lg:grid-cols-2"><Reveal className="rounded-2xl border border-teal/20 bg-teal/5 p-7"><ShieldCheck className="h-6 w-6 text-teal"/><h2 className="mt-5 text-xl font-semibold text-white">{copy.active}</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-300">{copy.activeItems.map(item=><li key={item}>{item}</li>)}</ul></Reveal><Reveal className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-7"><LockKeyhole className="h-6 w-6 text-amber-300"/><h2 className="mt-5 text-xl font-semibold text-white">{copy.todo}</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-300">{copy.todoItems.map(item=><li key={item}>{item}</li>)}</ul></Reveal></div></section>
  <section className="bg-slate-950 py-16"><Reveal className="mx-auto max-w-3xl px-4 text-center sm:px-6"><p className="text-sm leading-7 text-slate-400">{copy.note}</p></Reveal></section>
</PublicShell>}
