import type { Metadata } from "next";
import { HandCoins, History, Scale, ShieldCheck, Users } from "lucide-react";
import { SolutionDetail } from "@/components/landing/solution-detail";
import { getLocale } from "@/lib/i18n/server";

export const metadata: Metadata = { title: "Solution Groupe | AskFinance AI", description: "Dépenses partagées, soldes et règlements pour les groupes." };
const icons=[Users,Scale,HandCoins,History,ShieldCheck] as const;
const copies={
 fr:{eyebrow:"B2C · Groupe",title:"Partager les dépenses, pas les malentendus.",description:"Pour un couple, une colocation, un voyage ou un projet commun : chacun sait ce qu’il a payé, sa part et ce qu’il reste à régler.",promise:"Un registre commun, des soldes compréhensibles et un historique de confiance.",blocks:[["Membres invités","Un espace commun séparé des finances personnelles de chacun."],["Parts égales ou personnalisées","Répartissez chaque dépense selon la réalité du groupe."],["Qui doit à qui","Le moteur calcule les soldes nets et propose les règlements utiles."],["Règlements suivis","Un paiement peut être déclaré, confirmé ou contesté."],["Actions contrôlées","Seules les personnes concernées peuvent confirmer certaines opérations."]],steps:["Créez un espace Groupe et invitez les participants.","Ajoutez une dépense, son payeur et la répartition souhaitée.","Consultez automatiquement les soldes entre membres.","Déclarez puis confirmez les règlements pour garder un historique clair."],note:"Yassia n’est volontairement pas active dans les espaces Groupe tant qu’un ensemble d’outils dédié aux dépenses partagées n’est pas disponible. Le produit n’invente donc pas de recommandations sur des données qu’il ne sait pas encore exploiter."},
 en:{eyebrow:"B2C · Group",title:"Share expenses, not misunderstandings.",description:"For a couple, flatmates, a trip or a shared project: everyone knows what they paid, their share and what remains to settle.",promise:"A shared register, understandable balances and a trusted history.",blocks:[["Invited members","A shared workspace kept separate from everyone’s personal finances."],["Equal or custom shares","Split each expense according to the group’s reality."],["Who owes whom","The engine calculates net balances and suggests useful settlements."],["Tracked settlements","A payment can be declared, confirmed or disputed."],["Controlled actions","Only the people involved can confirm certain operations."]],steps:["Create a Group workspace and invite participants.","Add an expense, its payer and the desired split.","Automatically view balances between members.","Declare and confirm settlements to keep a clear history."],note:"Yassia is intentionally unavailable in Group workspaces until dedicated shared-expense tools are ready. The product therefore does not invent recommendations from data it cannot yet use properly."},
 uk:{eyebrow:"B2C · Група",title:"Діліть витрати, а не непорозуміння.",description:"Для пари, співмешканців, подорожі чи спільного проєкту: кожен бачить, що сплатив, свою частку й залишок до розрахунку.",promise:"Спільний реєстр, зрозумілі баланси й надійна історія.",blocks:[["Запрошені учасники","Спільний простір відокремлений від особистих фінансів кожного."],["Рівні або власні частки","Розподіляйте витрати відповідно до реальності групи."],["Хто кому винен","Система обчислює чисті баланси й пропонує потрібні розрахунки."],["Контроль розрахунків","Платіж можна заявити, підтвердити або оскаржити."],["Контрольовані дії","Лише залучені люди можуть підтверджувати певні операції."]],steps:["Створіть груповий простір і запросіть учасників.","Додайте витрату, платника й бажаний розподіл.","Автоматично переглядайте баланси між учасниками.","Заявляйте та підтверджуйте розрахунки для чіткої історії."],note:"Yassia навмисно не працює в групових просторах, доки не готові спеціальні інструменти спільних витрат. Продукт не вигадує рекомендацій із даних, які ще не може правильно опрацювати."},
} as const;
export default function GroupPage(){const c=copies[getLocale()];return <SolutionDetail eyebrow={c.eyebrow} title={c.title} description={c.description} promise={c.promise} blocks={c.blocks.map(([title,description],i)=>({icon:icons[i],title,description}))} steps={[...c.steps]} note={c.note}/>;}
