import Link from "next/link";
import { ArrowRight, Bot, BrainCircuit, CheckCircle2, Database, Gauge, ShieldAlert, Sparkles, TrendingUp } from "lucide-react";

import { PageHero } from "@/components/landing/page-hero";
import { PublicShell } from "@/components/landing/public-shell";
import { Reveal } from "@/components/landing/reveal";
import { Button } from "@/components/ui/button";
import { getLocale } from "@/lib/i18n/server";

const personaMeta = [[ShieldAlert,"text-amber-300 bg-amber-300/10"],[Gauge,"text-teal bg-teal/10"],[TrendingUp,"text-violet-300 bg-violet-300/10"]] as const;
const stepIcons = [BrainCircuit, Database, Bot] as const;
const copies = {
  fr: { eyebrow:"Yassia · Copilote IA", title:"Une IA qui va chercher les chiffres avant de répondre.", intro:"Yassia choisit les outils nécessaires, lit uniquement le périmètre de votre espace et adapte son angle à la décision que vous préparez.", try:"Essayer Yassia", personasEyebrow:"Les personas", personasTitle:"Même vérité financière. Trois façons de la regarder.", personaWord:"persona", personas:[["Prudence","Contrôleur","Sécuriser","Cherche d’abord les tensions de trésorerie, les anomalies, les doublons possibles et les engagements à surveiller.",["Qu’est-ce qui menace mon solde ?","Quelles charges ont augmenté ?","Que dois-je traiter cette semaine ?"]],["Pilotage","DAF","Arbitrer","Prépare une lecture structurée de la performance, hiérarchise les écarts et transforme les constats en décisions.",["Pourquoi ma marge évolue ?","Quels encaissements relancer ?","Quel point préparer avec mon comptable ?"]],["Croissance","Croissance","Projeter","Explore la capacité d’investissement, les marges de manœuvre et les conditions nécessaires à un scénario de développement.",["Puis-je investir ce trimestre ?","Quel budget augmenter ?","Quel scénario protège ma trésorerie ?"]]], how:"Fonctionnement", howTitle:"Pas une réponse générique collée sur votre dashboard.", howText:"La conversation est persistée dans votre espace. À chaque question, l’orchestrateur sélectionne les outils utiles puis transmet au modèle le contexte nécessaire à la réponse.", steps:[["1. Comprendre la demande","Le persona donne un angle, mais ne change pas les données."],["2. Appeler les bons outils","KPIs, budgets, prévisions, encaissements ou fiscalité selon la question."],["3. Expliquer et préparer","Yassia synthétise le constat, les limites et les prochaines actions."]], limitsTitle:"Ce que Yassia ne prétend pas faire", limits:["Remplacer un expert-comptable ou un conseil réglementé","Garantir une prévision ou un résultat futur","Accéder à un compte bancaire sans import explicite","Répondre dans un espace Groupe sans outils adaptés"] },
  en: { eyebrow:"Yassia · AI copilot", title:"AI that finds the numbers before answering.", intro:"Yassia selects the necessary tools, reads only your workspace scope and adapts its angle to the decision you are preparing.", try:"Try Yassia", personasEyebrow:"Personas", personasTitle:"The same financial truth. Three ways to view it.", personaWord:"persona", personas:[["Caution","Controller","Protect","Looks first for cash pressure, anomalies, possible duplicates and commitments to monitor.",["What threatens my balance?","Which charges increased?","What should I handle this week?"]],["Management","CFO","Arbitrate","Builds a structured performance review, prioritizes variances and turns findings into decisions.",["Why is my margin changing?","Which receivables should I chase?","What should I prepare with my accountant?"]],["Growth","Growth","Project","Explores investment capacity, room for manoeuvre and the conditions required for growth.",["Can I invest this quarter?","Which budget should increase?","Which scenario protects cash?"]]], how:"How it works", howTitle:"Not a generic answer pasted onto your dashboard.", howText:"The conversation is stored in your workspace. For each question, the orchestrator selects useful tools and passes only the context needed to answer.", steps:[["1. Understand the request","The persona provides an angle but does not alter the data."],["2. Call the right tools","KPIs, budgets, forecasts, receivables or tax depending on the question."],["3. Explain and prepare","Yassia summarizes the finding, limits and next actions."]], limitsTitle:"What Yassia does not claim to do", limits:["Replace an accountant or regulated adviser","Guarantee a forecast or future result","Access a bank account without an explicit import","Answer in a Group workspace without suitable tools"] },
  uk: { eyebrow:"Yassia · ШІ-помічник", title:"ШІ, який спочатку знаходить цифри, а потім відповідає.", intro:"Yassia обирає потрібні інструменти, читає лише дані вашого простору й адаптує погляд до рішення, яке ви готуєте.", try:"Спробувати Yassia", personasEyebrow:"Персони", personasTitle:"Одна фінансова правда. Три способи її побачити.", personaWord:"персона", personas:[["Обережність","Контролер","Захистити","Насамперед шукає ризики ліквідності, аномалії, можливі дублікати й зобов’язання для контролю.",["Що загрожує моєму балансу?","Які витрати зросли?","Що зробити цього тижня?"]],["Керування","CFO","Збалансувати","Готує структурований огляд, визначає пріоритети відхилень і перетворює спостереження на рішення.",["Чому змінюється маржа?","Які надходження нагадати?","Що підготувати з бухгалтером?"]],["Зростання","Зростання","Спрогнозувати","Досліджує інвестиційну спроможність, запас гнучкості й умови розвитку.",["Чи можу інвестувати цього кварталу?","Який бюджет збільшити?","Який сценарій захищає кошти?"]]], how:"Як це працює", howTitle:"Не загальна відповідь, вставлена в панель.", howText:"Розмова зберігається у вашому просторі. Для кожного питання оркестратор обирає інструменти й передає моделі лише потрібний контекст.", steps:[["1. Зрозуміти запит","Персона задає кут погляду, але не змінює дані."],["2. Викликати правильні інструменти","Показники, бюджети, прогнози, надходження або податки, залежно від питання."],["3. Пояснити й підготувати","Yassia підсумовує висновок, обмеження та наступні дії."]], limitsTitle:"Чого Yassia не обіцяє", limits:["Замінити бухгалтера чи регульованого консультанта","Гарантувати прогноз або майбутній результат","Дістати доступ до банку без явного імпорту","Відповідати в груповому просторі без відповідних інструментів"] },
} as const;

export default function AiPage() {
  const copy = copies[getLocale()];
  const personas = personaMeta.map(([icon,color],i) => ({icon,color,name:copy.personas[i][0],internal:copy.personas[i][1],objective:copy.personas[i][2],description:copy.personas[i][3],questions:copy.personas[i][4]}));
  const steps = stepIcons.map((Icon,i) => [Icon,copy.steps[i][0],copy.steps[i][1]] as const);
  return <PublicShell>
    <PageHero eyebrow={copy.eyebrow} title={copy.title} description={copy.intro}><Button asChild className="bg-white text-slate-950 hover:bg-slate-100"><Link href="/signup">{copy.try} <ArrowRight className="h-4 w-4" /></Link></Button></PageHero>
    <section className="bg-slate-950 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <Reveal className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-teal">{copy.personasEyebrow}</p><h2 className="mt-4 text-3xl font-semibold text-white sm:text-5xl">{copy.personasTitle}</h2></Reveal>
      <div className="mt-14 grid gap-5 lg:grid-cols-3">{personas.map((persona,index)=><Reveal key={persona.name} delay={index*0.07} className="rounded-2xl border border-white/10 bg-white/[0.035] p-6"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${persona.color}`}><persona.icon className="h-5 w-5"/></div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">{persona.objective} · {copy.personaWord} {persona.internal}</p><h3 className="mt-2 text-2xl font-semibold text-white">{persona.name}</h3><p className="mt-4 text-sm leading-6 text-slate-400">{persona.description}</p><ul className="mt-6 space-y-2 border-t border-white/10 pt-5">{persona.questions.map(question=><li key={question} className="flex gap-2 text-xs leading-5 text-slate-400"><Sparkles className="mt-0.5 h-3.5 w-3.5 shrink-0 text-teal"/>{question}</li>)}</ul></Reveal>)}</div>
    </div></section>
    <section className="border-y border-white/10 bg-slate-900/50 py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><Reveal><p className="text-sm font-semibold uppercase tracking-[0.2em] text-teal">{copy.how}</p><h2 className="mt-4 text-3xl font-semibold text-white sm:text-5xl">{copy.howTitle}</h2><p className="mt-5 text-lg leading-8 text-slate-400">{copy.howText}</p></Reveal><div className="space-y-4">{steps.map(([StepIcon,title,text],index)=><Reveal key={title} delay={index*0.06} className="flex gap-4 rounded-xl border border-white/10 bg-slate-950/70 p-5"><StepIcon className="mt-0.5 h-5 w-5 shrink-0 text-teal"/><div><h3 className="font-medium text-white">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-400">{text}</p></div></Reveal>)}</div></div></section>
    <section className="bg-slate-950 py-20"><div className="mx-auto max-w-5xl px-4 sm:px-6"><Reveal className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-6 sm:p-8"><h2 className="text-xl font-semibold text-white">{copy.limitsTitle}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{copy.limits.map(item=><p key={item} className="flex gap-2 text-sm leading-6 text-slate-300"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-amber-300"/>{item}</p>)}</div></Reveal></div></section>
  </PublicShell>;
}
