import type { Metadata } from "next";
import { Bot, LineChart, PiggyBank, Tags, WalletCards } from "lucide-react";
import { SolutionDetail } from "@/components/landing/solution-detail";
import { getLocale } from "@/lib/i18n/server";

export const metadata: Metadata = { title: "Solution Solo | AskFinance AI", description: "Budget personnel, dépenses et prévisions dans un espace privé." };
const icons=[WalletCards,PiggyBank,Tags,LineChart,Bot] as const;
const copies={
  fr:{eyebrow:"B2C · Solo",title:"Votre argent mérite mieux qu’un solde.",description:"Un espace personnel pour voir où part votre argent, ajuster chaque budget mensuel et anticiper ce qu’il vous restera.",promise:"Passer de « combien ai-je ? » à « que puis-je faire ? ».",blocks:[["Vue mensuelle","Revenus, dépenses, solde et reste du mois dans une lecture simple."],["Budgets variables","Un montant différent par catégorie et par mois, avec reprise du mois précédent."],["Catégories apprenantes","Vos corrections deviennent des règles pour les prochains imports."],["Prévision personnelle","Projection du solde avec les charges récurrentes observées."],["Coach IA personnel","Yassia répond avec un vocabulaire personnel, sans outils fiscaux d’entreprise."]],steps:["Créez un espace Solo et ajoutez votre compte avec son solde d’ouverture.","Importez un relevé CSV ; aucun accès bancaire permanent n’est demandé.","Ajustez vos catégories et vos budgets du mois.","Consultez la prévision ou demandez à Yassia où agir en priorité."],note:"Votre espace Solo reste distinct de vos espaces Groupe et Entreprise. Yassia y adopte un contexte personnel et ne formule pas de conseil fiscal professionnel."},
  en:{eyebrow:"B2C · Solo",title:"Your money deserves more than a balance.",description:"A personal workspace to see where your money goes, adjust each monthly budget and anticipate what will remain.",promise:"Move from “how much do I have?” to “what can I do?”.",blocks:[["Monthly view","Income, spending, balance and remaining amount in one clear view."],["Variable budgets","A different amount by category and month, copied from the previous month when useful."],["Learning categories","Your corrections become rules for future imports."],["Personal forecast","Balance projection based on observed recurring charges."],["Personal AI coach","Yassia uses personal language without business tax tools."]],steps:["Create a Solo workspace and add your account with its opening balance.","Import a CSV statement; no permanent bank access is requested.","Adjust this month’s categories and budgets.","Check the forecast or ask Yassia where to act first."],note:"Your Solo workspace stays separate from Group and Business workspaces. Yassia uses personal context and does not provide professional tax advice."},
  uk:{eyebrow:"B2C · Особисто",title:"Ваші гроші, це більше, ніж баланс.",description:"Особистий простір, щоб бачити витрати, налаштовувати місячні бюджети й прогнозувати залишок.",promise:"Перейдіть від «скільки я маю?» до «що я можу зробити?». ",blocks:[["Місячний огляд","Доходи, витрати, баланс і залишок місяця в одному зрозумілому поданні."],["Змінні бюджети","Різна сума за категорією й місяцем із можливістю повторити попередній місяць."],["Категорії, що навчаються","Ваші виправлення стають правилами для наступних імпортів."],["Особистий прогноз","Прогноз балансу з урахуванням регулярних витрат."],["Особистий ШІ-помічник","Yassia говорить у персональному контексті без бізнес-податкових інструментів."]],steps:["Створіть особистий простір і додайте рахунок із початковим балансом.","Імпортуйте CSV-виписку; постійний доступ до банку не потрібен.","Налаштуйте категорії та бюджет цього місяця.","Перегляньте прогноз або запитайте Yassia, що зробити насамперед."],note:"Особистий простір відокремлений від групових і бізнес-просторів. Yassia використовує персональний контекст і не надає професійних податкових порад."},
} as const;
export default function SoloPage(){const c=copies[getLocale()];return <SolutionDetail eyebrow={c.eyebrow} title={c.title} description={c.description} promise={c.promise} blocks={c.blocks.map(([title,description],i)=>({icon:icons[i],title,description}))} steps={[...c.steps]} note={c.note}/>;}
